# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4yKetc4SlYLVmtp3sXY1mdzRJwR3YiA
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

def generate_dataset(num_samples=200, seed=123):
    np.random.seed(seed)

    # Numeric continuous features
    age = np.random.randint(18, 70, size=num_samples)  # Age in years
    salary = np.random.normal(loc=60000, scale=15000, size=num_samples).astype(int)  # Annual salary in USD
    years_experience = np.clip(np.random.normal(loc=10, scale=5, size=num_samples), 0, None).astype(int)  # Years of experience

    # Categorical features
    departments = ['HR', 'IT', 'Finance', 'Marketing', 'Sales']
    department = np.random.choice(departments, size=num_samples)

    education_levels = ['High School', 'Bachelor', 'Master', 'PhD']
    education = np.random.choice(education_levels, size=num_samples, p=[0.2, 0.5, 0.25, 0.05])

    # Target / label - e.g., whether employee is a manager (binary)
    is_manager = (years_experience > 8) & (salary > 65000)
    is_manager = is_manager.astype(int)

    # Build DataFrame
    df = pd.DataFrame({
        'Age': age,
        'Salary': salary,
        'YearsExperience': years_experience,
        'Department': department,
        'EducationLevel': education,
        'IsManager': is_manager
    })

    return df

# Example usage
df = generate_dataset()
df.head()

"""Task 2: Department-wise Salary Distribution and Managerial Status

1. Create a boxplot showing the salary distribution for each department.
"""

# Create the boxplot
plt.figure(figsize=(10, 6))
sns.boxplot(x='Department', y='Salary', data=df, palette='pastel')

# Add titles and labels
plt.title('Salary Distribution by Department', fontsize=14)
plt.xlabel('Department', fontsize=12)
plt.ylabel('Salary ', fontsize=12)

# Show the plot
plt.tight_layout()
plt.show()

"""2. Overlay or color the data points by managerial status (IsManager) to observe how salaries differ for managers and non-managers within departments."""

df = generate_dataset()

# Set plot style
sns.set(style="whitegrid")

# Create the boxplot
plt.figure(figsize=(10, 6))
sns.boxplot(x='Department', y='Salary', data=df, palette='pastel')

# Overlay individual data points colored by IsManager
sns.stripplot(x='Department', y='Salary', data=df,
              hue='IsManager', dodge=True, jitter=True,
              marker='o', alpha=0.6, palette={0: 'red', 1: 'green'})

# Customize legend and labels
plt.title('Salary Distribution by Department with Managerial Status', fontsize=14)
plt.xlabel('Department', fontsize=12)
plt.ylabel('Salary', fontsize=12)
plt.legend(title='Is Manager', loc='upper right')

plt.tight_layout()
plt.show()

"""Summarize any differences in salary spread and median values among departments and between managerial groups


"""

# Generate the dataset
df = generate_dataset()

# Summary statistics by Department
dept_summary = df.groupby('Department')['Salary'].describe()
print("--> Salary Summary according to the each Department:\n")
print(dept_summary)

# Median salary by Department
dept_medians = df.groupby('Department')['Salary'].median()
print("\n --> Median Salary by each Department:\n")
print(dept_medians)

# Salary spread (IQR) by Department
dept_iqr = df.groupby('Department')['Salary'].agg(lambda x: np.percentile(x, 75) - np.percentile(x, 25))
print("\n --> Salary IQR (Interquartile Range) by Department:\n")
print(dept_iqr)

# Median salary by Managerial Status
manager_medians = df.groupby('IsManager')['Salary'].median()
print("\n --> Median Salary by Managerial Status:\n")
print(manager_medians)

# Salary spread by Managerial Status
manager_iqr = df.groupby('IsManager')['Salary'].agg(lambda x: np.percentile(x, 75) - np.percentile(x, 25))
print("\n -->Salary IQR by Managerial Status:\n")
print(manager_iqr)

"""**Note**
 : Finance and IT departments show the highest median salaries and widest spreads, indicating lucrative roles.
HR has the lowest median and tightest salary range, suggesting more uniform pay.
Managers earn significantly more, with higher medians and broader salary variation than non-managers.
Sales and Marketing show moderate medians but wide spreads, likely due to performance-based pay.

"""